/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayJNI */

#ifndef _Included_ArrayJNI
#define _Included_ArrayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayJNI
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ArrayJNI_sort01
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     ArrayJNI
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ArrayJNI_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     ArrayJNI
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ArrayJNI_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
