package zusapp;


import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.lang.management.ManagementFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.InstanceAlreadyExistsException;
import javax.management.MBeanRegistrationException;
import javax.management.MBeanServer;
import javax.management.MalformedObjectNameException;
import javax.management.NotCompliantMBeanException;
import javax.management.ObjectName;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Norbert
 */
public class ZUS extends javax.swing.JFrame implements ZUSMBean
{
    @Override
    public String doConfig()
    {
        return "No of cases=" + Integer.toString(this.caseCount);
    }

    @Override
    public int getCaseCount() {
        return caseCount;
    }

    @Override
    public void setCaseCount(int caseCount) {
        ZUS.caseCount = caseCount;
    }

    @Override
    public String[] getCategories() {
        return categories;
    }

    @Override
    public void setCategories(String[] categories) {
        this.categories = categories;
    }

    @Override
    public String getPendingCaseLabel() {
        return pendingCaseLabel.getText();
    }

    @Override
    public void setPendingCaseLabel(String pendingCaseLabel) {
        this.pendingCaseLabel.setText(pendingCaseLabel);
    }
    
    private static int caseCount = 0;
    private String[] categories = {"PAYMENT", "WITHDRAWAL", "BILLING", "INFORMATION"};
    private ArrayList<String[]> tasks = new ArrayList<String[]>();

    /**
     * Creates new form ZUS
     */
    public ZUS() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        caseListTable = new javax.swing.JTable();
        selectCaseTypeBox = new javax.swing.JComboBox<>();
        getNumberButton = new javax.swing.JButton();
        resolveCaseButton = new javax.swing.JButton();
        pendingCaseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZUS NUMBER GENERATOR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select action"));

        caseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LP", "NUMBER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(caseListTable);

        selectCaseTypeBox.setModel(new DefaultComboBoxModel(categories));
        selectCaseTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCaseTypeBoxActionPerformed(evt);
            }
        });

        getNumberButton.setText("get NUMBER");
        getNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNumberButtonActionPerformed(evt);
            }
        });

        resolveCaseButton.setText("resolve CASE");
        resolveCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveCaseButtonActionPerformed(evt);
            }
        });

        pendingCaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingCaseLabel.setText("Pending: ...");
        pendingCaseLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pendingCaseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectCaseTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getNumberButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resolveCaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pendingCaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectCaseTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(getNumberButton)
                .addGap(18, 18, 18)
                .addComponent(resolveCaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingCaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNumberButtonActionPerformed
        
        String caseName = selectCaseTypeBox.getSelectedItem().toString();
       
        DefaultTableModel model = (DefaultTableModel) caseListTable.getModel();
        
        String rowData[] = new String[3];
        rowData[0] = Integer.toString(caseCount);
        rowData[1] = caseName.substring(0, 2) + "-" + ZUS.caseCount;
        rowData[2] = caseName;
     
      
        if(tasks.size() == 0)
        {
            pendingCaseLabel.setText(rowData[1].toString());            
        }

        
        tasks.add(rowData);
        model.addRow(rowData); 
        
        ZUS.caseCount++;

    }//GEN-LAST:event_getNumberButtonActionPerformed

    private void resolveCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveCaseButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) caseListTable.getModel();
        
        if(getTask(tasks, pendingCaseLabel.getText()) == -1)
        {
            System.err.println("No tasks to resolve");
        }
        
        else
        {
            for(int i=0; i < ZUS.caseCount;i++)
            {
                if(caseListTable.getValueAt(i, 1).equals(pendingCaseLabel.getText()))
                {
                    model.removeRow(i);
                    break;
                }
            }
            
            tasks.remove(getTask(tasks, pendingCaseLabel.getText()));
            
            assignTaskPriority(tasks);
        }
        
        ZUS.caseCount--;
        
    }//GEN-LAST:event_resolveCaseButtonActionPerformed

    private void selectCaseTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCaseTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCaseTypeBoxActionPerformed

    private int getTask(ArrayList<String[]> list, String pattern)
    {
        for (String[] item : list) 
        {
            if(item[1].equals(pattern))
            {
                return list.indexOf(item);
            }
        }
        return -1;
    }
    
    private void assignTaskPriority(ArrayList<String[]> list)
    {
        if(!list.isEmpty())
        {
            Random rand = new Random();
            String[] randomElement = list.get(rand.nextInt(list.size()));
            pendingCaseLabel.setText(randomElement[1]);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedObjectNameException, InstanceAlreadyExistsException, InstanceAlreadyExistsException, MBeanRegistrationException, NotCompliantMBeanException, InterruptedException 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        //Get the MBean server
        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        //register the MBean
        ZUS mBean = new ZUS();
        ObjectName name = new ObjectName("zusapp.ZUS.jmx:type=ZUSCONFIG");
        try 
        {
            mbs.registerMBean(mBean, name);
        } 
        catch (NotCompliantMBeanException ex) 
        {
            Logger.getLogger(ZUS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        mBean.setVisible(true);
        do
        {
            Thread.sleep(3000);
            System.out.println("Case Count="+mBean.getCaseCount());
        }
        while(mBean.getCaseCount() !=0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable caseListTable;
    private javax.swing.JButton getNumberButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pendingCaseLabel;
    private javax.swing.JButton resolveCaseButton;
    private javax.swing.JComboBox<String> selectCaseTypeBox;
    // End of variables declaration//GEN-END:variables
}



